const CANONICAL_ORIGIN = 'https://liveparse.com';
const DIRECTORY_ROUTES = new Set([
  '/ko/json-parser',
  '/json-formatter',
  '/json-repair',
  '/jsonl-parser',
  '/json-to-csv',
  '/csv-to-json',
  '/json-compare',
  '/unix-timestamp-converter',
  '/discord-timestamp-generator',
  '/base64-decoder',
  '/base64-encoder',
  '/binary-converter',
  '/hex-converter',
  '/binary-translator',
  '/ascii-table',
  '/morse-code-translator',
  '/image-compressor',
  '/compress-image-to-20kb',
  '/compress-image-to-50kb',
  '/compress-image-to-100kb',
  '/compress-image-to-200kb',
  '/compress-image-to-500kb',
  '/compress-image-to-1mb',
  '/image-resizer',
  '/png-to-jpg',
  '/webp-to-jpg',
  '/webp-to-png',
  '/age-calculator',
  '/age-calculator-on-specific-date',
  '/date-calculator',
  '/days-between-dates',
  '/business-days-calculator',
  '/2-business-days-from-today',
  '/3-business-days-from-today',
  '/4-business-days-from-today',
  '/5-business-days-from-today',
  '/7-business-days-from-today',
  '/10-business-days-from-today',
  '/14-business-days-from-today',
  '/15-business-days-from-today',
  '/20-business-days-from-today',
  '/30-business-days-from-today',
  '/45-business-days-from-today',
  '/morse-code-alphabet',
  '/time-duration-calculator',
  '/week-number-calculator',
  '/birthday-countdown',
  '/word-counter',
  '/character-counter',
  '/es/contador-de-palabras',
  '/es/contador-de-caracteres',
  '/ja/character-counter',
  '/ko/character-counter',
  '/url-encoder',
  '/url-decoder',
  '/url-parser',
  '/query-string-parser',
  '/hash-generator',
  '/sha256-generator',
  '/md5-generator',
  '/file-checksum',
  '/uuid-generator',
  '/uuid-v4-generator',
  '/uuid-v7-generator',
  '/uuid-validator',
  '/uuid-decoder',
  '/jwt-decoder',
  '/jwt-expiration-checker',
  '/sql-formatter',
  '/mysql-sql-formatter',
  '/postgresql-sql-formatter',
  '/bigquery-sql-formatter',
  '/sql-server-formatter',
  '/xml-formatter',
  '/xml-validator',
  '/xml-viewer',
  '/yaml-formatter',
  '/yaml-validator',
  '/yaml-viewer',
  '/yaml-to-json',
  '/json-to-yaml',
  '/privacy',
  '/about',
  '/guides',
  '/guides/what-is-a-json-parser',
  '/guides/common-json-errors',
  '/guides/json-parser-vs-formatter-validator',
  '/guides/compare-api-responses',
  '/guides/compare-json-ignore-order',
  '/guides/unix-timestamp-seconds-vs-milliseconds',
  '/guides/unix-timestamp-code-examples',
  '/guides/discord-timestamp-formats',
  '/guides/base64-vs-base64url',
  '/guides/binary-decimal-hex-octal-conversion',
  '/guides/twos-complement-signed-binary',
  '/guides/ascii-vs-unicode-utf8',
  '/guides/how-word-counting-works',
  '/guides/grapheme-clusters-vs-code-points-and-bytes',
  '/guides/international-morse-code',
  '/guides/image-compression-formats-and-file-size',
  '/guides/calendar-date-arithmetic-dst-leap-years',
  '/guides/uuid-v4-vs-v7',
  '/guides/uuid-versions-explained',
  '/guides/uuid-collision-probability',
  '/guides/jwt-decode-vs-verify',
  '/guides/sql-dialect-formatting',
  '/guides/xml-well-formed-vs-valid',
  '/guides/yaml-1-1-vs-1-2',
  '/guides/yaml-to-json-types',
  '/guides/yaml-anchors-aliases-merge-keys',
  '/guides/common-yaml-errors',
  '/guides/sha256-vs-md5',
  '/guides/hash-vs-encryption',
  '/guides/how-to-verify-file-checksum',
  '/guides/hashing-utf8-newlines',
  '/guides/url-percent-encoding',
  '/guides/encodeuri-vs-encodeuricomponent',
  '/guides/percent20-vs-plus',
  '/guides/double-url-encoding',
]);
const ROUTE_REDIRECTS = new Map([
  ['/json-parser', '/json-formatter/'],
  ['/json-parser/', '/json-formatter/'],
  ['/json-validator', '/json-formatter/'],
  ['/json-validator/', '/json-formatter/'],
  ['/json-beautifier', '/json-formatter/'],
  ['/json-beautifier/', '/json-formatter/'],
  ['/json-viewer', '/json-formatter/'],
  ['/json-viewer/', '/json-formatter/'],
  ['/format-json', '/json-formatter/'],
  ['/format-json/', '/json-formatter/'],
  ['/parse-json', '/json-formatter/'],
  ['/parse-json/', '/json-formatter/'],
  ['/json-diff', '/json-compare/'],
  ['/json-diff/', '/json-compare/'],
  ['/json-diff-checker', '/json-compare/'],
  ['/json-diff-checker/', '/json-compare/'],
  ['/epoch-converter', '/unix-timestamp-converter/'],
  ['/epoch-converter/', '/unix-timestamp-converter/'],
  ['/epoch-time-converter', '/unix-timestamp-converter/'],
  ['/epoch-time-converter/', '/unix-timestamp-converter/'],
  ['/timestamp-converter', '/unix-timestamp-converter/'],
  ['/timestamp-converter/', '/unix-timestamp-converter/'],
  ['/unix-time-converter', '/unix-timestamp-converter/'],
  ['/unix-time-converter/', '/unix-timestamp-converter/'],
  ['/discord-timestamp', '/discord-timestamp-generator/'],
  ['/discord-timestamp/', '/discord-timestamp-generator/'],
  ['/discord-timestamp-converter', '/discord-timestamp-generator/'],
  ['/discord-timestamp-converter/', '/discord-timestamp-generator/'],
  ['/discord-time-converter', '/discord-timestamp-generator/'],
  ['/discord-time-converter/', '/discord-timestamp-generator/'],
  ['/discord-time-generator', '/discord-timestamp-generator/'],
  ['/discord-time-generator/', '/discord-timestamp-generator/'],
  ['/base64-decode', '/base64-decoder/'],
  ['/base64-decode/', '/base64-decoder/'],
  ['/base64-encode', '/base64-encoder/'],
  ['/base64-encode/', '/base64-encoder/'],
  ['/base64-encoder-decoder', '/base64-decoder/'],
  ['/base64-encoder-decoder/', '/base64-decoder/'],
  ['/binary-to-decimal', '/binary-converter/'],
  ['/binary-to-decimal/', '/binary-converter/'],
  ['/decimal-to-binary', '/binary-converter/'],
  ['/decimal-to-binary/', '/binary-converter/'],
  ['/base-converter', '/binary-converter/'],
  ['/base-converter/', '/binary-converter/'],
  ['/number-base-converter', '/binary-converter/'],
  ['/number-base-converter/', '/binary-converter/'],
  ['/hex-to-decimal', '/hex-converter/'],
  ['/hex-to-decimal/', '/hex-converter/'],
  ['/decimal-to-hex', '/hex-converter/'],
  ['/decimal-to-hex/', '/hex-converter/'],
  ['/hexadecimal-converter', '/hex-converter/'],
  ['/hexadecimal-converter/', '/hex-converter/'],
  ['/binary-to-text', '/binary-translator/'],
  ['/binary-to-text/', '/binary-translator/'],
  ['/text-to-binary', '/binary-translator/'],
  ['/text-to-binary/', '/binary-translator/'],
  ['/ascii-chart', '/ascii-table/'],
  ['/ascii-chart/', '/ascii-table/'],
  ['/ascii-code-table', '/ascii-table/'],
  ['/ascii-code-table/', '/ascii-table/'],
  ['/ascii-codes', '/ascii-table/'],
  ['/ascii-codes/', '/ascii-table/'],
  ['/morse-code-decoder', '/morse-code-translator/'],
  ['/morse-code-decoder/', '/morse-code-translator/'],
  ['/morse-translator', '/morse-code-translator/'],
  ['/morse-translator/', '/morse-code-translator/'],
  ['/text-to-morse-code', '/morse-code-translator/'],
  ['/text-to-morse-code/', '/morse-code-translator/'],
  ['/morse-code-converter', '/morse-code-translator/'],
  ['/morse-code-converter/', '/morse-code-translator/'],
  ['/compress-image', '/image-compressor/'],
  ['/compress-image/', '/image-compressor/'],
  ['/compress-jpeg-to-100kb', '/compress-image-to-100kb/'],
  ['/compress-jpeg-to-100kb/', '/compress-image-to-100kb/'],
  ['/compress-png-to-100kb', '/compress-image-to-100kb/'],
  ['/compress-png-to-100kb/', '/compress-image-to-100kb/'],
  ['/compress-jpeg-to-200kb', '/compress-image-to-200kb/'],
  ['/compress-jpeg-to-200kb/', '/compress-image-to-200kb/'],
  ['/compress-image-to-1024kb', '/compress-image-to-1mb/'],
  ['/compress-image-to-1024kb/', '/compress-image-to-1mb/'],
  ['/reduce-image-size-to-100kb', '/compress-image-to-100kb/'],
  ['/reduce-image-size-to-100kb/', '/compress-image-to-100kb/'],
  ['/compress-photo-to-1mb', '/compress-image-to-1mb/'],
  ['/compress-photo-to-1mb/', '/compress-image-to-1mb/'],
  ['/image-compress', '/image-compressor/'],
  ['/image-compress/', '/image-compressor/'],
  ['/photo-compressor', '/image-compressor/'],
  ['/photo-compressor/', '/image-compressor/'],
  ['/reduce-image-size', '/image-compressor/'],
  ['/reduce-image-size/', '/image-compressor/'],
  ['/reduce-image-size-in-kb', '/image-compressor/'],
  ['/reduce-image-size-in-kb/', '/image-compressor/'],
  ['/resize-image', '/image-resizer/'],
  ['/resize-image/', '/image-resizer/'],
  ['/photo-resizer', '/image-resizer/'],
  ['/photo-resizer/', '/image-resizer/'],
  ['/resize-photo', '/image-resizer/'],
  ['/resize-photo/', '/image-resizer/'],
  ['/pixel-resizer', '/image-resizer/'],
  ['/pixel-resizer/', '/image-resizer/'],
  ['/png-to-jpeg', '/png-to-jpg/'],
  ['/png-to-jpeg/', '/png-to-jpg/'],
  ['/convert-png-to-jpg', '/png-to-jpg/'],
  ['/convert-png-to-jpg/', '/png-to-jpg/'],
  ['/convert-png-to-jpeg', '/png-to-jpg/'],
  ['/convert-png-to-jpeg/', '/png-to-jpg/'],
  ['/webp-to-jpeg', '/webp-to-jpg/'],
  ['/webp-to-jpeg/', '/webp-to-jpg/'],
  ['/convert-webp-to-jpg', '/webp-to-jpg/'],
  ['/convert-webp-to-jpg/', '/webp-to-jpg/'],
  ['/convert-webp-to-jpeg', '/webp-to-jpg/'],
  ['/convert-webp-to-jpeg/', '/webp-to-jpg/'],
  ['/convert-webp-to-png', '/webp-to-png/'],
  ['/convert-webp-to-png/', '/webp-to-png/'],
  ['/calculate-age', '/age-calculator/'],
  ['/calculate-age/', '/age-calculator/'],
  ['/date-of-birth-calculator', '/age-calculator/'],
  ['/date-of-birth-calculator/', '/age-calculator/'],
  ['/dob-calculator', '/age-calculator/'],
  ['/dob-calculator/', '/age-calculator/'],
  ['/how-old-am-i', '/age-calculator/'],
  ['/how-old-am-i/', '/age-calculator/'],
  ['/age-on-date', '/age-calculator-on-specific-date/'],
  ['/age-on-date/', '/age-calculator-on-specific-date/'],
  ['/chronological-age-calculator', '/age-calculator-on-specific-date/'],
  ['/chronological-age-calculator/', '/age-calculator-on-specific-date/'],
  ['/add-days-to-date', '/date-calculator/'],
  ['/add-days-to-date/', '/date-calculator/'],
  ['/date-add-calculator', '/date-calculator/'],
  ['/date-add-calculator/', '/date-calculator/'],
  ['/days-from-today', '/date-calculator/'],
  ['/days-from-today/', '/date-calculator/'],
  ['/date-difference-calculator', '/days-between-dates/'],
  ['/date-difference-calculator/', '/days-between-dates/'],
  ['/day-counter', '/days-between-dates/'],
  ['/day-counter/', '/days-between-dates/'],
  ['/days-calculator', '/days-between-dates/'],
  ['/days-calculator/', '/days-between-dates/'],
  ['/working-days-calculator', '/business-days-calculator/'],
  ['/working-days-calculator/', '/business-days-calculator/'],
  ['/workdays-calculator', '/business-days-calculator/'],
  ['/workdays-calculator/', '/business-days-calculator/'],
  ['/business-days-from-today', '/business-days-calculator/'],
  ['/business-days-from-today/', '/business-days-calculator/'],
  ['/business-day-calculator', '/business-days-calculator/'],
  ['/business-day-calculator/', '/business-days-calculator/'],
  ['/morse-alphabet', '/morse-code-alphabet/'],
  ['/morse-alphabet/', '/morse-code-alphabet/'],
  ['/morse-code-chart', '/morse-code-alphabet/'],
  ['/morse-code-chart/', '/morse-code-alphabet/'],
  ['/morse-code-letters', '/morse-code-alphabet/'],
  ['/morse-code-letters/', '/morse-code-alphabet/'],
  ['/morse-code-numbers', '/morse-code-alphabet/'],
  ['/morse-code-numbers/', '/morse-code-alphabet/'],
  ['/hours-calculator', '/time-duration-calculator/'],
  ['/hours-calculator/', '/time-duration-calculator/'],
  ['/time-difference-calculator', '/time-duration-calculator/'],
  ['/time-difference-calculator/', '/time-duration-calculator/'],
  ['/iso-week-number', '/week-number-calculator/'],
  ['/iso-week-number/', '/week-number-calculator/'],
  ['/week-number', '/week-number-calculator/'],
  ['/week-number/', '/week-number-calculator/'],
  ['/birthday-calculator', '/birthday-countdown/'],
  ['/birthday-calculator/', '/birthday-countdown/'],
  ['/days-until-my-birthday', '/birthday-countdown/'],
  ['/days-until-my-birthday/', '/birthday-countdown/'],
  ['/word-count', '/word-counter/'],
  ['/word-count/', '/word-counter/'],
  ['/word-count-checker', '/word-counter/'],
  ['/word-count-checker/', '/word-counter/'],
  ['/character-count', '/character-counter/'],
  ['/character-count/', '/character-counter/'],
  ['/letter-counter', '/character-counter/'],
  ['/letter-counter/', '/character-counter/'],
  ['/es/contador-palabras', '/es/contador-de-palabras/'],
  ['/es/contador-palabras/', '/es/contador-de-palabras/'],
  ['/es/contar-palabras', '/es/contador-de-palabras/'],
  ['/es/contar-palabras/', '/es/contador-de-palabras/'],
  ['/es/contador-caracteres', '/es/contador-de-caracteres/'],
  ['/es/contador-caracteres/', '/es/contador-de-caracteres/'],
  ['/es/contar-caracteres', '/es/contador-de-caracteres/'],
  ['/es/contar-caracteres/', '/es/contador-de-caracteres/'],
  ['/url-encode', '/url-encoder/'],
  ['/url-encode/', '/url-encoder/'],
  ['/encode-url', '/url-encoder/'],
  ['/encode-url/', '/url-encoder/'],
  ['/urlencode', '/url-encoder/'],
  ['/urlencode/', '/url-encoder/'],
  ['/percent-encoder', '/url-encoder/'],
  ['/percent-encoder/', '/url-encoder/'],
  ['/url-decode', '/url-decoder/'],
  ['/url-decode/', '/url-decoder/'],
  ['/decode-url', '/url-decoder/'],
  ['/decode-url/', '/url-decoder/'],
  ['/urldecode', '/url-decoder/'],
  ['/urldecode/', '/url-decoder/'],
  ['/percent-decoder', '/url-decoder/'],
  ['/percent-decoder/', '/url-decoder/'],
  ['/parse-url', '/url-parser/'],
  ['/parse-url/', '/url-parser/'],
  ['/url-inspector', '/url-parser/'],
  ['/url-inspector/', '/url-parser/'],
  ['/url-analyzer', '/url-parser/'],
  ['/url-analyzer/', '/url-parser/'],
  ['/query-string', '/query-string-parser/'],
  ['/query-string/', '/query-string-parser/'],
  ['/query-parser', '/query-string-parser/'],
  ['/query-parser/', '/query-string-parser/'],
  ['/parse-query-string', '/query-string-parser/'],
  ['/parse-query-string/', '/query-string-parser/'],
  ['/url-query-parser', '/query-string-parser/'],
  ['/url-query-parser/', '/query-string-parser/'],
  ['/hash', '/hash-generator/'],
  ['/hash/', '/hash-generator/'],
  ['/hashing-tool', '/hash-generator/'],
  ['/hashing-tool/', '/hash-generator/'],
  ['/online-hash-generator', '/hash-generator/'],
  ['/online-hash-generator/', '/hash-generator/'],
  ['/sha-256-generator', '/sha256-generator/'],
  ['/sha-256-generator/', '/sha256-generator/'],
  ['/sha256-hash', '/sha256-generator/'],
  ['/sha256-hash/', '/sha256-generator/'],
  ['/sha256', '/sha256-generator/'],
  ['/sha256/', '/sha256-generator/'],
  ['/md5-hash-generator', '/md5-generator/'],
  ['/md5-hash-generator/', '/md5-generator/'],
  ['/md5-hash', '/md5-generator/'],
  ['/md5-hash/', '/md5-generator/'],
  ['/md5', '/md5-generator/'],
  ['/md5/', '/md5-generator/'],
  ['/checksum', '/file-checksum/'],
  ['/checksum/', '/file-checksum/'],
  ['/checksum-calculator', '/file-checksum/'],
  ['/checksum-calculator/', '/file-checksum/'],
  ['/file-hash', '/file-checksum/'],
  ['/file-hash/', '/file-checksum/'],
  ['/file-hash-calculator', '/file-checksum/'],
  ['/file-hash-calculator/', '/file-checksum/'],
  ['/guid-generator', '/uuid-generator/'],
  ['/guid-generator/', '/uuid-generator/'],
  ['/generate-uuid', '/uuid-generator/'],
  ['/generate-uuid/', '/uuid-generator/'],
  ['/uuid-generator-online', '/uuid-generator/'],
  ['/uuid-generator-online/', '/uuid-generator/'],
  ['/uuid-v4', '/uuid-v4-generator/'],
  ['/uuid-v4/', '/uuid-v4-generator/'],
  ['/uuid4-generator', '/uuid-v4-generator/'],
  ['/uuid4-generator/', '/uuid-v4-generator/'],
  ['/generate-uuid-v4', '/uuid-v4-generator/'],
  ['/generate-uuid-v4/', '/uuid-v4-generator/'],
  ['/guid-v4-generator', '/uuid-v4-generator/'],
  ['/guid-v4-generator/', '/uuid-v4-generator/'],
  ['/uuid-v7', '/uuid-v7-generator/'],
  ['/uuid-v7/', '/uuid-v7-generator/'],
  ['/uuid-checker', '/uuid-validator/'],
  ['/uuid-checker/', '/uuid-validator/'],
  ['/uuid-decode', '/uuid-decoder/'],
  ['/uuid-decode/', '/uuid-decoder/'],
  ['/decode-uuid', '/uuid-decoder/'],
  ['/decode-uuid/', '/uuid-decoder/'],
  ['/uuid-parser', '/uuid-decoder/'],
  ['/uuid-parser/', '/uuid-decoder/'],
  ['/uuid-inspector', '/uuid-decoder/'],
  ['/uuid-inspector/', '/uuid-decoder/'],
  ['/guid-decoder', '/uuid-decoder/'],
  ['/guid-decoder/', '/uuid-decoder/'],
  ['/jwt-decode', '/jwt-decoder/'],
  ['/jwt-decode/', '/jwt-decoder/'],
  ['/decode-jwt', '/jwt-decoder/'],
  ['/decode-jwt/', '/jwt-decoder/'],
  ['/jwt-parser', '/jwt-decoder/'],
  ['/jwt-parser/', '/jwt-decoder/'],
  ['/jwt-debugger', '/jwt-decoder/'],
  ['/jwt-debugger/', '/jwt-decoder/'],
  ['/jwt-inspector', '/jwt-decoder/'],
  ['/jwt-inspector/', '/jwt-decoder/'],
  ['/jwt-token-decoder', '/jwt-decoder/'],
  ['/jwt-token-decoder/', '/jwt-decoder/'],
  ['/json-web-token-decoder', '/jwt-decoder/'],
  ['/json-web-token-decoder/', '/jwt-decoder/'],
  ['/jwt-exp-checker', '/jwt-expiration-checker/'],
  ['/jwt-exp-checker/', '/jwt-expiration-checker/'],
  ['/jwt-expiry-checker', '/jwt-expiration-checker/'],
  ['/jwt-expiry-checker/', '/jwt-expiration-checker/'],
  ['/jwt-token-expiration-checker', '/jwt-expiration-checker/'],
  ['/jwt-token-expiration-checker/', '/jwt-expiration-checker/'],
  ['/sql-format', '/sql-formatter/'],
  ['/sql-format/', '/sql-formatter/'],
  ['/format-sql', '/sql-formatter/'],
  ['/format-sql/', '/sql-formatter/'],
  ['/sql-query-formatter', '/sql-formatter/'],
  ['/sql-query-formatter/', '/sql-formatter/'],
  ['/sql-beautifier', '/sql-formatter/'],
  ['/sql-beautifier/', '/sql-formatter/'],
  ['/sql-pretty-printer', '/sql-formatter/'],
  ['/sql-pretty-printer/', '/sql-formatter/'],
  ['/online-sql-formatter', '/sql-formatter/'],
  ['/online-sql-formatter/', '/sql-formatter/'],
  ['/mysql-formatter', '/mysql-sql-formatter/'],
  ['/mysql-formatter/', '/mysql-sql-formatter/'],
  ['/mysql-query-formatter', '/mysql-sql-formatter/'],
  ['/mysql-query-formatter/', '/mysql-sql-formatter/'],
  ['/postgresql-formatter', '/postgresql-sql-formatter/'],
  ['/postgresql-formatter/', '/postgresql-sql-formatter/'],
  ['/postgres-formatter', '/postgresql-sql-formatter/'],
  ['/postgres-formatter/', '/postgresql-sql-formatter/'],
  ['/postgres-query-formatter', '/postgresql-sql-formatter/'],
  ['/postgres-query-formatter/', '/postgresql-sql-formatter/'],
  ['/bigquery-formatter', '/bigquery-sql-formatter/'],
  ['/bigquery-formatter/', '/bigquery-sql-formatter/'],
  ['/google-sql-formatter', '/bigquery-sql-formatter/'],
  ['/google-sql-formatter/', '/bigquery-sql-formatter/'],
  ['/tsql-formatter', '/sql-server-formatter/'],
  ['/tsql-formatter/', '/sql-server-formatter/'],
  ['/t-sql-formatter', '/sql-server-formatter/'],
  ['/t-sql-formatter/', '/sql-server-formatter/'],
  ['/mssql-formatter', '/sql-server-formatter/'],
  ['/mssql-formatter/', '/sql-server-formatter/'],
  ['/sql-server-sql-formatter', '/sql-server-formatter/'],
  ['/sql-server-sql-formatter/', '/sql-server-formatter/'],
  ['/xml-format', '/xml-formatter/'],
  ['/xml-format/', '/xml-formatter/'],
  ['/format-xml', '/xml-formatter/'],
  ['/format-xml/', '/xml-formatter/'],
  ['/xml-beautifier', '/xml-formatter/'],
  ['/xml-beautifier/', '/xml-formatter/'],
  ['/xml-pretty-printer', '/xml-formatter/'],
  ['/xml-pretty-printer/', '/xml-formatter/'],
  ['/online-xml-formatter', '/xml-formatter/'],
  ['/online-xml-formatter/', '/xml-formatter/'],
  ['/xml-formatter-online', '/xml-formatter/'],
  ['/xml-formatter-online/', '/xml-formatter/'],
  ['/validate-xml', '/xml-validator/'],
  ['/validate-xml/', '/xml-validator/'],
  ['/xml-validation', '/xml-validator/'],
  ['/xml-validation/', '/xml-validator/'],
  ['/xml-checker', '/xml-validator/'],
  ['/xml-checker/', '/xml-validator/'],
  ['/xml-syntax-checker', '/xml-validator/'],
  ['/xml-syntax-checker/', '/xml-validator/'],
  ['/online-xml-validator', '/xml-validator/'],
  ['/online-xml-validator/', '/xml-validator/'],
  ['/xml-validator-online', '/xml-validator/'],
  ['/xml-validator-online/', '/xml-validator/'],
  ['/view-xml', '/xml-viewer/'],
  ['/view-xml/', '/xml-viewer/'],
  ['/xml-tree-viewer', '/xml-viewer/'],
  ['/xml-tree-viewer/', '/xml-viewer/'],
  ['/online-xml-viewer', '/xml-viewer/'],
  ['/online-xml-viewer/', '/xml-viewer/'],
  ['/xml-viewer-online', '/xml-viewer/'],
  ['/xml-viewer-online/', '/xml-viewer/'],
  ['/yaml-beautifier', '/yaml-formatter/'],
  ['/yaml-beautifier/', '/yaml-formatter/'],
  ['/yaml-prettify', '/yaml-formatter/'],
  ['/yaml-prettify/', '/yaml-formatter/'],
  ['/format-yaml', '/yaml-formatter/'],
  ['/format-yaml/', '/yaml-formatter/'],
  ['/yml-formatter', '/yaml-formatter/'],
  ['/yml-formatter/', '/yaml-formatter/'],
  ['/yml-validator', '/yaml-validator/'],
  ['/yml-validator/', '/yaml-validator/'],
  ['/validate-yaml', '/yaml-validator/'],
  ['/validate-yaml/', '/yaml-validator/'],
  ['/yaml-checker', '/yaml-validator/'],
  ['/yaml-checker/', '/yaml-validator/'],
  ['/yaml-parser', '/yaml-viewer/'],
  ['/yaml-parser/', '/yaml-viewer/'],
  ['/yaml-tree-viewer', '/yaml-viewer/'],
  ['/yaml-tree-viewer/', '/yaml-viewer/'],
  ['/view-yaml', '/yaml-viewer/'],
  ['/view-yaml/', '/yaml-viewer/'],
  ['/convert-yaml-to-json', '/yaml-to-json/'],
  ['/convert-yaml-to-json/', '/yaml-to-json/'],
  ['/yml-to-json', '/yaml-to-json/'],
  ['/yml-to-json/', '/yaml-to-json/'],
  ['/convert-json-to-yaml', '/json-to-yaml/'],
  ['/convert-json-to-yaml/', '/json-to-yaml/'],
  ['/json-to-yml', '/json-to-yaml/'],
  ['/json-to-yml/', '/json-to-yaml/'],
]);

function normalizeKnownRoutePath(pathname) {
  if (ROUTE_REDIRECTS.has(pathname)) return ROUTE_REDIRECTS.get(pathname);
  if (DIRECTORY_ROUTES.has(pathname)) return `${pathname}/`;
  if (pathname === '/index.html') return '/';
  if (pathname.endsWith('/index.html')) return pathname.slice(0, -'index.html'.length);
  return pathname;
}

function securityHeaders(headers) {
  headers.set('Content-Security-Policy', [
    "default-src 'self'",
    "base-uri 'self'",
    "connect-src 'self'",
    "font-src 'self'",
    "form-action 'self'",
    "frame-src 'none'",
    "frame-ancestors 'none'",
    "img-src 'self' data: blob:",
    "manifest-src 'self'",
    "object-src 'none'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "worker-src 'self'",
    'upgrade-insecure-requests',
  ].join('; '));
  headers.set('Cross-Origin-Opener-Policy', 'same-origin');
  headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  headers.set('Strict-Transport-Security', 'max-age=63072000; includeSubDomains; preload');
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('X-Frame-Options', 'DENY');
  headers.set('Permissions-Policy', 'camera=(), geolocation=(), microphone=(), payment=(), usb=()');
  return headers;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.hostname === 'www.liveparse.com' || (url.hostname === 'liveparse.com' && url.protocol !== 'https:')) {
      return Response.redirect(`${CANONICAL_ORIGIN}${normalizeKnownRoutePath(url.pathname)}${url.search}`, 308);
    }
    if (ROUTE_REDIRECTS.has(url.pathname)) {
      url.pathname = ROUTE_REDIRECTS.get(url.pathname);
      return Response.redirect(url.toString(), 308);
    }
    if (DIRECTORY_ROUTES.has(url.pathname)) {
      // Keep private/preview Sites hosts on their current origin while still
      // normalizing the public liveparse.com URL to its canonical slash form.
      url.pathname = `${url.pathname}/`;
      return Response.redirect(url.toString(), 308);
    }
    if (url.pathname === '/index.html' || url.pathname.endsWith('/index.html')) {
      url.pathname = url.pathname === '/index.html' ? '/' : url.pathname.slice(0, -'index.html'.length);
      return Response.redirect(url.toString(), 308);
    }

    const assetResponse = await env.ASSETS.fetch(request);
    const headers = securityHeaders(new Headers(assetResponse.headers));

    if (url.pathname === '/feed.xml') {
      headers.set('Content-Type', 'application/atom+xml; charset=utf-8');
    }

    if (url.hostname !== 'liveparse.com' && url.hostname !== 'www.liveparse.com') {
      headers.set('X-Robots-Tag', 'noindex, nofollow');
    }

    if (url.pathname.startsWith('/assets/') && /-[A-Za-z0-9_-]{8,}\.[^/]+$/.test(url.pathname)) {
      headers.set('Cache-Control', 'public, max-age=31536000, immutable');
    } else if ((headers.get('Content-Type') || '').includes('text/html')) {
      // `no-transform` keeps the CDN from injecting the RUM beacon into HTML.
      headers.set('Cache-Control', 'no-cache, no-transform');
    }

    return new Response(assetResponse.body, {
      status: assetResponse.status,
      statusText: assetResponse.statusText,
      headers,
    });
  },
};
